Fix NULL users?
When the following options are enabled in Nextcloud 13.0.0 the ContactsMenu fails to load.
```
Restrict users to only share with users in their groups
Allow username autocompletion in share dialog. If this is disabled the full username or email address needs to be entered.
```

The issue is traced back to:
### /lib/private/Contacts/ContactsMenu/ContactsStore.php
```PHP
$contactGroups = $this->groupManager->getUserGroupIds($this->userManager->get($entry->getProperty('UID')));
```

You'll get the error:
```
TypeError: Argument 1 passed to OC\Group\Manager::getUserGroupIds() must implement interface OCP\IUser, null given, called in /nextcloud/lib/private/Contacts/ContactsMenu/ContactsStore.php on line 161
```