Update MemoryInfo.php
fixed memoryLimitToBytes function, which was causing TypeError on some servers, when memory_limit in php.ini was writen as non numeric. the error was:
TypeError: Return value of OC\MemoryInfo::memoryLimitToBytes() must be of the type integer, float returned